In [1]:
import numpy as np

In [2]:
np.zeros(5) # Parameter Turing

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(5,dtype=int) # Hyperparameter Turring 
# machin 

array([0, 0, 0, 0, 0])

In [5]:
np.zeros((2,2)) # parameter tunnig 

array([[0., 0.],
       [0., 0.]])

In [6]:
np.zeros((2,3),dtype=int) # Hyperparameter Turring 

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
np.zeros((10,10),dtype=int) # first no is Row and second are Coloum

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones(4)# parameter tunnig 

array([1., 1., 1., 1.])

In [10]:
np.ones((2,3),dtype=int) # Hyperparameter Turring 

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [14]:
random.rand(2,3)

NameError: name 'random' is not defined

In [15]:
np.random.rand(2)

array([0.37193406, 0.00786176])

In [16]:
np.random.rand(2)

array([0.70954186, 0.59748502])

In [17]:
np.random.rand(2,3) # it is gentre the only float values 

array([[0.01593555, 0.45275269, 0.19046895],
       [0.65086948, 0.62807635, 0.52217798]])

In [22]:
np.random.randint(2)  # it will generate the  random interger number 

1

In [28]:
np.random.randint(2,9) # it will generate the  random interger  between into 2 to 9 

8

In [ ]:
np.random.randint(2,9,4) # it will generate the  random interger  between

In [29]:
import secrets

otp = "".join(str(secrets.randbelow(10)) for _ in range(6))
print("Your OTP is:", otp)


Your OTP is: 867300


In [ ]:
def generate_otp(length=4):
    otp='',join(str (np.random.randint(1,10)for _in range ()))

In [31]:
np.random.randint(10,40,(10,10))

array([[29, 31, 10, 37, 26, 30, 33, 37, 34, 10],
       [39, 38, 17, 33, 20, 28, 20, 25, 29, 26],
       [13, 38, 16, 10, 10, 19, 18, 15, 12, 27],
       [30, 29, 38, 28, 38, 20, 17, 34, 17, 29],
       [21, 26, 14, 26, 15, 36, 25, 30, 34, 36],
       [31, 16, 17, 33, 36, 13, 14, 27, 12, 32],
       [11, 11, 19, 31, 39, 20, 26, 11, 25, 39],
       [34, 29, 36, 39, 22, 10, 24, 28, 11, 27],
       [18, 35, 30, 29, 39, 12, 32, 33, 34, 21],
       [38, 14, 25, 33, 12, 16, 21, 34, 15, 38]])

In [32]:
arr1=np.random.randint(10,40,(10,10))
print(arr1)

[[36 18 11 20 25 10 29 16 20 28]
 [27 22 24 10 11 16 11 27 24 39]
 [31 30 35 10 26 19 27 19 24 22]
 [14 10 16 29 23 10 16 34 18 15]
 [32 10 11 30 35 27 28 14 19 32]
 [39 10 14 32 21 31 19 35 17 27]
 [36 10 31 28 33 26 14 16 34 38]
 [15 22 26 13 28 28 28 20 26 25]
 [31 35 25 34 24 36 22 10 25 39]
 [12 20 17 26 21 36 33 10 34 29]]


In [33]:
print(arr1)

[[36 18 11 20 25 10 29 16 20 28]
 [27 22 24 10 11 16 11 27 24 39]
 [31 30 35 10 26 19 27 19 24 22]
 [14 10 16 29 23 10 16 34 18 15]
 [32 10 11 30 35 27 28 14 19 32]
 [39 10 14 32 21 31 19 35 17 27]
 [36 10 31 28 33 26 14 16 34 38]
 [15 22 26 13 28 28 28 20 26 25]
 [31 35 25 34 24 36 22 10 25 39]
 [12 20 17 26 21 36 33 10 34 29]]


In [35]:
arr1[-2]

array([31, 35, 25, 34, 24, 36, 22, 10, 25, 39])

In [34]:
arr1[5]

array([39, 10, 14, 32, 21, 31, 19, 35, 17, 27])

In [42]:
arr2=np.random.randint(2,9,(5,5))
print(arr2)

[[8 8 2 7 7]
 [5 7 5 8 6]
 [8 6 5 7 8]
 [5 7 3 2 5]
 [6 5 3 8 6]]


In [47]:
arr2[3,4]

5

In [46]:
print(arr2[-3, -4])

6


In [48]:
arr2

array([[8, 8, 2, 7, 7],
       [5, 7, 5, 8, 6],
       [8, 6, 5, 7, 8],
       [5, 7, 3, 2, 5],
       [6, 5, 3, 8, 6]])

In [52]:
print(arr2[-3,-4])


6


In [ ]:
arr2[:,0] # pprint the coloum in array matrix

array([8, 5, 8, 5, 6])

In [55]:
arr2[:,-3]

array([2, 5, 5, 3, 3])

In [ ]:
arr

# Masking on fillter in numpy

In [56]:
arr2

array([[8, 8, 2, 7, 7],
       [5, 7, 5, 8, 6],
       [8, 6, 5, 7, 8],
       [5, 7, 3, 2, 5],
       [6, 5, 3, 8, 6]])

In [57]:
arr2>5

array([[ True,  True, False,  True,  True],
       [False,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [False,  True, False, False, False],
       [ True, False, False,  True,  True]])

In [ ]:
arr2[arr2>=5]  # Filter into the numpy

array([8, 8, 7, 7, 7, 8, 6, 8, 6, 7, 8, 7, 6, 8, 6])

In [59]:
arr2[arr2>=5]  # Filter into the numpy

array([8, 8, 7, 7, 5, 7, 5, 8, 6, 8, 6, 5, 7, 8, 5, 7, 5, 6, 5, 8, 6])

In [60]:
arr2[arr2==5]  # Filter into the numpy

array([5, 5, 5, 5, 5, 5])

In [61]:
arr2[arr2!=5]  # Filter into the numpy

array([8, 8, 2, 7, 7, 7, 8, 6, 8, 6, 7, 8, 7, 3, 2, 6, 3, 8, 6])

In [ ]:
arr2.reshape(5,4) 

ValueError: cannot reshape array of size 25 into shape (5,4)

In [ ]:
a = int(input())
b = int(input())
c = int(input())

print(a, b, c)
del c
print(a, b)

a= int(input())
b= int(input())
c=int(input())

print(a,b,c)
del(c)
print(a,b)

4 5 5
4 5
12 13 14
12 13


# 1. ARRAY CREATION  FUNCTION

In [2]:
import numpy as np

In [3]:
f= np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation 

In [5]:
a1=np.array([1,2,3])
reshaped =np.reshape(a1,(1,3))
print("reshaped array",reshaped)

reshaped array [[1 2 3]]


In [ ]:
a1=np.array([1,2,3])
reshaped =np.reshape(a1,(1,3))
print("reshaped array",reshaped)

In [11]:
f1= np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened =np.ravel(f1)
print(f1)
print("Flanttened array :",flattened)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Flanttened array : [ 1  2  3  4  5  6  7  8  9 10]


In [12]:
e1 = np.array([[1,2],[3,4]])
transposed= np.transpose(e1)
print(e1)
print("Transposed array:\n" ,transposed)


[[1 2]
 [3 4]]
Transposed array:
 [[1 3]
 [2 4]]


In [ ]:
a2 =np.array([1,2])
b2=np.array([3,4])
stacked= np.vstack([a2,b2])
print(a2,b2)
print(" v stacked array:\n",stacked)

[1 2] [3 4]
stacked array:
 [[1 2]
 [3 4]]


In [14]:
a2 =np.array([1,2])
b2=np.array([3,4])
stacked= np.hstack([a2,b2])
print(a2,b2)
print("H stacked array:\n",stacked)

[1 2] [3 4]
H stacked array:
 [1 2 3 4]


# math operation in numpy


In [16]:
g = np.array([1,2,3,4])
added =np.add(g,2)
print("Added " ,g)

Added  [1 2 3 4]


In [17]:
squared=np.power (g,2)
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [ ]:

print(a)

NameError: name 'a' is not defined

In [22]:
a=np.array([1,2,3])
a3=np.array([1,2,3])
dot_product= np.dot(a1,a)
print("dot productof a1 and a",dot_product)

dot productof a1 and a 14


In [28]:
s = np.array([1,2,3])
mean =np.mean(s)
print(s)
print("Mean of s:",mean)

[1 2 3]
Mean of s: 2.0


In [29]:
var =np.var(s)
print(s)
print("Varisace of s:",var)

[1 2 3]
Varisace of s: 0.6666666666666666


In [ ]:
std_dev=np.std(s)
print(s)
print("Varisace of s:",std_dev) # standart deviaction

[1 2 3]
Varisace of s: 0.816496580927726


In [32]:
minium = np.min(s)
print("Min of s:",minium)

Min of s: 1


In [34]:
maxium = np.max(s)
print("Max of s:",maxium)

Max of s: 3


# linear algebra 

In [ ]:
matrix 

# random sampling function

In [36]:
random_vals=np.random.rand(3)
print("Random values",random_vals)

Random values [0.08755542 0.6351708  0.16594812]


In [ ]:
np.random.seed(0)
random

In [37]:
rand_ints =np.random.randint(0,10,size=4)
print("random",rand_ints )

random [2 6 9 2]


In [47]:
# np.random.seed(0)
rand_ints =np.random.randint(0,10,size=5)
print("random integer ",rand_ints )

random integer  [5 9 8 9 4]


In [48]:
np.random.seed(0)
rand_ints =np.random.randint(0,10,size=5)
print("random integer ",rand_ints )

random integer  [5 0 3 3 7]
